### ISSUE TITLE
[Feature] support for `(it|test|describe).each(...)`

### ISSUE THREAD

**Issue by atk** [vitest-dev/vitest#120]
Jest supports `it.each`: https://jestjs.io/docs/api#testeachtablename-fn-timeout with an array or a template table.

**Comment by kirillgroshkov** [comment]
> but at least users could migrate from Jest without changing their code

Would be awesome! 🙏 

I've just tested migrating some of my smaller repos from Jest to Vitest, and found 2 broken things:
1. lack of `test.each`
2. lack of `expect().rejects` support (but this one is somewhat easier to mitigate/refactor in userland)

**Comment by kirillgroshkov** [comment]
15 minutes after writing last comment, managed to "money-patch" the missing `test.each` support by using this quick&dirty function (and my tests pass now 🚀 )

```ts
export function testEach(cases: any[][]): (name: string, fn: AnyFunction) => void {
  return (name, fn) => {
    cases.forEach(items => {
      test(name, () => fn(...items))
    })
  }
}
```

**Comment by oliverzy** [comment]
+1 for this feature.

![image](https://user-images.githubusercontent.com/1321817/147666258-ec7b42f1-83c1-4325-abc3-7f6941a600c3.png)

**Comment by joshacheson** [comment]
I tried the solution shared by @kirillgroshkov and found that though my tests passed, they weren't actually running. I tried using really basic sanity checks like `expect(true).toBe(false)` and got no failures. The callback of `testEach(set)(name, callback)` was running for each member of `set`, but `describe`, `it` and `test` calls inside the callback were not actually resulting in the tests being run.

[stackblitz here](https://stackblitz.com/edit/node-fgfv4e?file=test/basic.test.ts)

Two thoughts on my mind:

1) There might have actually been a change in the behaviour of `vitest` for this situation in the 20 days since this solution was suggested.
2) The behaviour I'm describing above may be intuitive for folks who know more about how `vitest` works.

**Comment by kirillgroshkov** [comment]
`testEach` returns a function, maybe you forgot to call it?

e.g `testEach(...)()`

That would explain why you go no failures of basic checks.

**Comment by privatenumber** [comment]
Would like this request to cover [`describe.each()`](https://jestjs.io/docs/api#describeeachtablename-fn-timeout) too.

**Comment by hmt** [comment]
Thank you very much! I was asking for this feature just today on Discord. Highly appreciated!!!

**Comment by sidharthv96** [comment]
I was migrating [MermaidJS](https://github.com/mermaid-js/mermaid/) to vitest and needed template literal support. 
Wrote a simple function as a hack to convert template literals to Object array.

https://gist.github.com/sidharthv96/80cc25016d94b6f6590dec89e6586c64
