### ISSUE TITLE
Vitest spyOn has different behaviour than jest's 

### ISSUE THREAD

**Issue by galkatz373** [vitest-dev/vitest#1329]
### Describe the bug

Hey!
It seems the vitest spyOn doesn't have the same behaviour as the jest's (see reproduction)

### Reproduction

vitest project reproduction: https://stackblitz.com/edit/vitest-dev-vitest-ne8pti?file=src%2Fexample.ts,test%2Fbasic.test.ts,package.json&initialPath=__vitest__

jest project reproduction: https://github.com/galkatz373/jest-example

### System Info

```shell
macOS 12.0.1, node 16.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not about `spyOn`, but about how babel transforms typescript files.

Vite transforms files to something like this:
```js
const func = () => {}
const combine = () => {
  func()
}
Object.definePropertry(__vite_exports__, 'func', {
  get: () => func
})
Object.definePropertry(__vite_exports__, 'combine', {
  get: () => combine
})
```
`spyOn` just spies on a call to `__vite_exports__.func`, but since `func` was called as a standalone function, we cannot spy on it.

I assume, babel saves pointers to functions somehow.

This is out of scope of Vitest. Maybe you can point to Vite repo for the solution. I will not close this issue now, in case you have any questions.

**Comment by galkatz373** [comment]
Thanks for the quick response! what would you say the workaround? besides potentially changing vite itself

**Comment by sheremet-va** [comment]
If you store methods on an object or class, you can spy on them without problem:
```ts
// funcs.ts
class Helper {
  func() {}
  
  combine() {
    this.func()
  }
}

export const helper = new Helper()

// or

export const helper = {
  func: () => {},
  combine: () => {
    helper.func()
  }
}

// test.ts
import { helper } from './funcs'

vi.spyOn(helper, 'func').mockReturnOnce(100)
```

**Comment by gugadev** [comment]
@sheremet-va works as well without instances but class level? For example, Helper class is injected by DI inside a Component and I want to test the component by mocking the class methods. Does Vitest support something like `vi.spyOn(Helper.prototype, "func").mockReturnOnce(100)`? Thanks.

**Comment by sheremet-va** [comment]
> @sheremet-va works as well without instances but class level? For example, Helper class is injected by DI inside a Component and I want to test the component by mocking the class methods. Does Vitest support something like `vi.spyOn(Helper.prototype, "func").mockReturnOnce(100)`? Thanks.

Yes, it works.

**Comment by unicornware** [comment]
> > @sheremet-va works as well without instances but class level? For example, Helper class is injected by DI inside a Component and I want to test the component by mocking the class methods. Does Vitest support something like `vi.spyOn(Helper.prototype, "func").mockReturnOnce(100)`? Thanks.
> 
> Yes, it works.

@sheremet-va

are there any docs or examples regarding class level spies? i've scoured the docs site, but didn't see any references. not sure if i'm just overlooking them, however.

i'm finding that **call counts are not recorded with a class level spy**. my goal is to ensure the method `updateRepository` has been called once (`toHaveBeenCalledOnce`).  i've tried the following patterns:

- `vi.spyOn(Manager.prototype, 'updateRepository')`
-  `vi.spyOn(Manager.default.prototype, 'updateRepository')` (the `Manager` class is `default` exported)
- mocking `Manager`, then using `vi.mock('#src/models/manager')` instead of `vi.spyOn`

any thoughts?
