### ISSUE TITLE
Add option to define the system timezone for tests

### ISSUE THREAD

**Issue by mikeybinnswebdesign** [vitest-dev/vitest#1575]
### Clear and concise description of the problem

There is currently no way to set the timezone for a set of tests.
I'd like a way to be able to set the current timezone of the test system for use with the Date function for testing.

### Suggested solution

Locally in tests.
```
beforeEach(() => {
    vi.setTimezone('UTC'); 
    // or
    vi.setTimezone('Europe/London'); 
    // or
    vi.setTimezone('GMT+05');
})
```
or globally:
```
export default defineConfig({
	test: {
		timezone:'UTC',
	},
});
```

### Alternative

I've tried setting the timezone via .env and process.env.TZ, both seem to be pretty unreliable.

### Additional context

This is an example of a test to run after setting the environment to ensure the timezone is set correctly.
```
describe("Test Env Checks", () => {
	it("should always be UTC", () => {
		expect(new Date().getTimezoneOffset()).toBe(0);
	});
});
```
or

```
describe("Test Env Checks", () => {
	it("should always be GMT+01", () => {
		expect(new Date().getTimezoneOffset()).toBe(-60);
	});
});
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Run `TZ=UTC vitest`

**Comment by mikeybinnswebdesign** [comment]
Thanks, that solves for the global basis, would be nice if there was a way to change it for different tests, but I understand that's probably really hard to implement, so happy to call this closed 👍

**Comment by sheremet-va** [comment]
I don't think this is possible to do dynamically within Vitest. Please, use `TZ=UTC` syntax when running Vitest.

**Comment by lnhrdt** [comment]
> Run `TZ=UTC vitest`

Relying on the TZ env var to be set like this on the command line (or by the `package.json` script) didn't very well for my team. In our development workflow we run our tests in a variety of ways including in our IDEs. While the IDEs pick up the vitest environment configuration just fine, they're not aware of how we've configured the test script in `package.json`. Getting this configuration right across workstations has been cumbersome for us and we thought if the configuration for this TZ env var could be done centrally (with the rest of our test environment's configuration) that would make much more sense because we would automatically be configured properly in every environment and on every workstation.

We tried setting the TZ env var in a [`setupFiles`](https://vitest.dev/config/#setupfiles) script but it didn't work. Trying to set it using `process.env.TZ=...` or using `vi.stubEnv('TZ', '...')` seemed to have no affect (i.e. the libraries we use that can be configured with the TZ env var were still defaulting to the system timezone).

**However, we did find a working solution by setting the TZ env var in a [`globalSetup`](https://vitest.dev/config/#globalsetup) script.** We had to use the `process.env.TZ=...` syntax because when we tried using `vi.stubEnv('TZ', '...')` the test runner said importing `vitest` wasn't allowed in `globalSetup` (nice helpful error message btw).

Here's our final solution in case it helps others:
```ts
// src/test-globals.ts
export const setup = () => {
  process.env.TZ = 'US/Eastern'
}
```

```ts
// vitest.config.ts
import {mergeConfig} from 'vite'
import {defineConfig} from 'vitest/config'
import viteConfig from './vite.config'

export default mergeConfig(viteConfig, defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    globalSetup: './src/test-globals.ts',
    setupFiles: './src/test-env.tsx',
  },
}))
```

**Comment by phawxby** [comment]
I'd also like to add that using `TZ=UTC` doesn't work well for windows users. Sure, you can use `cross-env` or some such but I'd rather not rely on a package that's essentially frozen. Being able to specify `tz: 'UTC'` in the config and have that implement the process above but much more simply would be very helpful.

**Comment by donalmurtagh** [comment]
> You can pass down env variables with test.env config option:

This didn't work for me. I set the following in `vite.config.js`

```javascript
export default defineConfig(({ mode }) => {
  const config = {
    test: {
      env: {
        TZ: 'UTC'
      }
    }
  }

  return config
})
```

Then ran the following test and it failed
```javascript
describe('date utils tests', () => {

  it('timezone should return UTC', () => {
   // my local timezone 'Europe/Dublin' was returned for process.env.TV
    expect(process.env.TZ).toBe('UTC')
  })
})
```

**Comment by mikeybinns** [comment]
@donalmurtagh it won't work if you set the timezone in the config because by the time you reach the point where vitest reads it, it's too late.

You must set the env variable before you run the vitest command, e.g.

`TZ=UTC vitest`

**Comment by donalmurtagh** [comment]
@mikeybinns 

> Have you tried setting other ENV variables with a different name? Or accessing the env variables via import.meta.env.VAR_NAME?

No, I tried [this approach](https://github.com/vitest-dev/vitest/issues/1575#issuecomment-1439286286) and it worked.
