### ISSUE TITLE
Coverage with HTML reporter (c8) for .vue + .ts files, no SFC

### ISSUE THREAD

**Issue by OrestHk** [vitest-dev/vitest#1839]
### Describe the bug

Hi, updating vitest from `0.16` to `0.21.1` I found out the following

`yarn vitest --coverage` with an `html` reporter will throw an error when the component that is tested is not a SFC (.vue + .ts), as the reporter will list the ts file as `file.ts?vue&type=script&src=true&lang.ts`

The same error occurs for a project using vue@2.7, @vue/test-utils@1 with the last version of vitest

Rollbacking to `0.16` it seems that the ts file does not appear at all in the report, only the .vue file is listed

Sorry if I missed something in the documentation about that case !

### Reproduction

https://github.com/OrestHk/vitest-coverage-no-sfc

- yarn install
- yarn vitest --coverage

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    Memory: 6.30 GB / 15.85 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.81
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^3.0.1 => 3.0.1
    vite: ^3.0.5 => 3.0.5
    vitest: ^0.21.1 => 0.21.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cub** [comment]
Same here, in a Vue component, with his script in a dedicated file, outside .vue file :
```html
<template>
  <div class="my-component">Hello world</div>
</template>
<script lang="ts" src="./my-component.ts"></script>
```

In the coverage summary output in the terminal, we can see a `?vue&type=script&src=true&lang.ts` after the filename :
![image](https://user-images.githubusercontent.com/1578812/195394892-8659ff7f-2c34-4e03-85c3-54da09afe4d5.png)

In the lcov-report html generated, filenames have the same problem. HTML link are broken :
![image](https://user-images.githubusercontent.com/1578812/195395026-6ec3c975-bbd2-4e6c-acab-05ed8c1bb208.png)

If I open manually the html file, the `istanbul-lib-report` fail at resolve source :
![image](https://user-images.githubusercontent.com/1578812/195395967-e0dd87ec-cac4-4d37-94a9-e3851c78b087.png)

Here my test config :
```js
test: {
  environment: 'jsdom',
  passWithNoTests: true,
  cache: false,
  watch: false,
  setupFiles: ['./vitest.setup.js'],
  reporters: ['default', 'vitest-sonar-reporter'],
  outputFile: path.resolve(__dirname, './test-report.xml'),
  coverage: {
    enabled: true,
    reporter: ['json', 'lcov', 'text', 'clover', 'text-summary'],
    include: ['src/components/**/*.ts', 'src/utils/**/*.ts'],
    exclude: ['**/node_modules/**']
  }
}
```

I was able to "fix" 🙈 by monkey patching the lib `istanbul-lib-report` in `context.js`
```js
getSource(filePath) {
  return this.sourceFinder(filePath.replaceAll('?vue&type=script&src=true&lang.ts', ''));
}
```
and in `path.js`
```js
function makeRelativeNormalizedPath(str, sep) {
    const parsed = parsePath(str);
    let root = parsed.root;
    let dir;
    let file = parsed.base.replaceAll('?vue&type=script&src=true&lang.ts', '');
    let quoted;
    let pos;
```
But I think the problem is upstream in Vitest.
