### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node' is not defined by "exports"

### ISSUE THREAD

**Issue by coure2011** [vitest-dev/vitest#1884]
### Describe the bug

Its throwing error when trying to `import { BaseSequencer } from 'vitest/node';`

### Reproduction

Just download any sample and try to add
`import { BaseSequencer } from 'vitest/node';`

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.66 GB / 15.73 GB
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-legacy: 2.0.0 => 2.0.0
    @vitejs/plugin-vue2: 1.1.2 => 1.1.2
    vite: 3.0.2 => 3.0.2
    vitest: 0.22.1 => 0.22.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't bundle CJS version. You need to enable `"type": "module"` in your `package.json` or rename config to `vite.config.mts`/`vite.config.mjs`.

**Comment by abdul-alhasany** [comment]
Is there a possibility of reconsidering this? I mean bundling a CJS version.

My use case is that I am creating a VSCode extension. I was able to successfully use vite to bundle the extension and I would like to conduct testing using vitest. Unfortunately VSCode is built on top electron which only uses commonjs. 

I tried to include vitest using a hacky method, like so:
```js
const vitestNodeModules = path.resolve(__dirname, '../../node_modules/vitest/dist/node.js');

const { startVitest } = await import(pathToFileURL(vitestNodeModules).href);
	const vitest = await startVitest('test', [], {
		watch: false,
		dir: path.resolve(__dirname, '..'),
	});
```
This, however, did not work and caused a myriad of other issues.

I am using JavasSript API because vscode runs the tests in a separate process and it is impossible to run it directly. I wasted a whole day trying to figure out how to make them work together. 

I can use mocha framework but I prefer vitest in this case for two reasons:

-  I already use vite in my project and its working fine. I want to have a single configuration between test and build process so I can utilize paths alias and other configurations.
- I already use vitest in other parts of the project (it is a monorepo) and it is working fine. It will be easier to maintain if the testing framework was the same across the entire codebase.

I hope there is a reconsideration of this issue until electronjs moves to ESM (if ever).
