### ISSUE TITLE
Istanbul Coverage + Svelte: Incorrectly Identifying an If / Else Block

### ISSUE THREAD

**Issue by kgladfelder** [vitest-dev/vitest#1893]
### Describe the bug

In a svelte.kit application, while outputting data in an each block, any time the iterator is accessed, Istanbul is reporting that I never go into an `if` block that doesn't exist. Also, in the coverage report it shows line 97 as partially covered and the HTML shows it as fully covered.

![image](https://user-images.githubusercontent.com/39464447/185800908-e840eeab-17cf-4b5b-a40f-409b4ea4953f.png)

![image](https://user-images.githubusercontent.com/39464447/185800926-26afebad-0517-449f-8266-e1e5a83d3fd8.png)

### Reproduction

https://github.com/kgladfelder/vitest-issue-repro

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 7.88 GB / 15.86 GB
  npmPackages:
    vite: ^3.0.7 => 3.0.7
    vitest: ^0.22.0 => 0.22.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
I don't think there is anything we can do on Vitest's codebase. Changes in Svelte compiler could fix this.

Looking at @kgladfelder's repro we can see that Svelte compiler is adding helper-functions which end up getting instrumented. I think these helper functions are included in source maps so that debugging tools can stop on breakpoints. But when instrumenting code, we end up collecting coverage from these unnecessary if-blocks. When the transpiled code is mapped back to sources, we can see covered and uncovered lines on unexpected lines+columns.

This is why `}</span>` is seen in coverage report as uncovered:

Look at these lines+columns in sources:

```js
12 |   <span>{result.gameName}</span>
                              ^^^^^
```

In the transpiled code those map into this single character here:

```js
225 |   if (dirty & /*searchResults*/ 1 && t0$_value$ !== (t0$_value$ = /*result*/ ctx[2].gameName + "")) set_data_dev$(t0$, t0$_value$);
                                                                                                 ^
```

Now looking at the instrumented transpiled code. A branch counter is added here. When code is executed it is never reached.
This will mark those original lines in source code as uncovered.

```js
4980 |      if ((cov_1a56qtdo1c().b[7][0]++, dirty &
4981 |      /*searchResults*/
4982 |      1) && (cov_1a56qtdo1c().b[7][1]++, t0$_value$ !== (t0$_value$ =
4983 |      /*result*/
4984 |      ctx[2].gameName + ""))) {
4985 |        cov_1a56qtdo1c().b[6][0]++;
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Branch counter!
4986 |        cov_1a56qtdo1c().s[92]++;
4987 |        set_data_dev$(t0$, t0$_value$);
4988 |      } else {
```

In the same repro repo there are also some 100% correctly working source maps. Here is one example:

```js
16 |  {#if !searched}
            ^^^^^^^^
17 |   <h6>Please search for a game.</h6>
18 |  {:else}
```

```js
44 | if (!/*searched*/ ctx[1]) return create_if_block$;
                       ^^^
```

```js
4672 |    if (!
4673 |    /*searched*/
4674 |    ctx[1]) {
4675 |      cov_1a56qtdo1c().b[0][0]++;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ Branch counter!
4676 |      cov_1a56qtdo1c().s[6]++;
4677 |      return create_if_block$;
4678 |    } else {
```

I'm 99% sure I've seen some code transformer tool adding `/* istanbul ignore */` comments around their helper functions. I think it was in Babel's codebase but can't find it anymore.

A possible solution here would be if Svelte compiler excluded its helper functions from instrumenters.

**Comment by AriPerkkio** [comment]
Upstream issue open https://github.com/sveltejs/svelte/issues/7824.
