### ISSUE TITLE
Force exist on certain timeout

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#191]
In some cases, user code might contain unsolved callbacks that keep the process running without shutting down, which might cause the CI to never ends. We need to add a timer to force end the process and error out after some amount of time when the tests are done.

**Comment by AlexandrHoroshih** [comment]
Hello! @antfu 

Did the Vitest team decided not to add this feature? 😢

It would be very useful for those of us, who is migrating from Jest - as Jest does exactly this, which allows to, at least, solve the problem in non-blocking way

I think this could be something like `vitest run --forceExit` 🤔

I like Vitest a lot and overall experience is very good, but because we had some leaky tests in our codebase, we are now doing this:

```js
// scripts/vitest_ci.mjs
import 'zx/globals';

await $`yarn vitest run`;

setTimeout(() => {
  console.log('Unresolved promise somewhere :(');
  $`exit`;
}, 5_000);
```

Which is similiar to how Jest does this under the hood:
https://github.com/facebook/jest/blob/main/packages/jest-cli/src/run.ts#L111

**Comment by sheremet-va** [comment]
> Did the Vitest team decided not to add this feature? 😢

What do you mean? It's implemented in this same issue, and controlled by [`teardownTimeout`](https://vitest.dev/config/#teardowntimeout) config option

**Comment by AlexandrHoroshih** [comment]
Hmm, it seems it is enabled by default - it didn't work for us 🤔 
I will try to research and return with more information

**Comment by AlexandrHoroshih** [comment]
@sheremet-va 

I also tried to check in the Vitest sources - looks like, teardown actually should happen at the `vitest/node/cli-wrapper` level 🤔 
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/cli-wrapper.ts

Because currently teardown happens at the `vitest/node/cli`, which is later spawned at `cli-wrapper` as a separate child process via `execa`
