### ISSUE TITLE
Problem with importing lodash when configured as noExternal

### ISSUE THREAD

**Issue by jiby-aurum** [vitest-dev/vitest#2345]
### Describe the bug

when `lodash` is configured to be inlined with 

```
ssr: {
    noExternal: [/lodash/],
},
```

then `import { isString } from 'lodash'` will get `isString === undefined`. Works fine when `lodash` is not in noExternal. 

### Reproduction

https://stackblitz.com/edit/vitest-lodash-issue-uvdn9b

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 684.47 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.1.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5423.0
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
The default behavior of `lodash` is `external`
ref: `_shouldExternalize` -> `isValidNodeImport` 
https://github.com/vitest-dev/vitest/blob/3038991347500f1336089698a3517ee5c5a5b4f3/packages/vite-node/src/externalize.ts#L84
Since lodash  is CJS  -> this make it as `external` automatic

Force setting `noExternal:lodash` will make vitest load the `lodash.js`  (as a main entry of package.json)
in node_module and could not get the correct declaration.
https://github.com/lodash/lodash/blob/master/package.json

If you use ESM version
https://www.npmjs.com/package/lodash-es

I think it will be fixed.

**Comment by jiby-aurum** [comment]
@azaleta this makes sense, I think the reason I added `lodash` to external was because otherwise vite was then generating the ssr build wrong, I don't fully remember. I finally went with a conditional config that avoid externalisation only during ssr build.

Will try out `lodash-es`, as it would be cool to then get rid of this conditional config.

**Comment by sheremet-va** [comment]
Yea, `lodash` doesn't support this usage in Node.js.
