### ISSUE TITLE
Vitest cli not working

### ISSUE THREAD

**Issue by WolfgangVing** [vitest-dev/vitest#2352]
### Describe the bug

After following the website instruction, and tried to run `vitest --config ./path/to/vitest.config.ts`  I get , and for every vitest cli command is the same.
```PowerShell
vitest: The term 'vitest' is not recognized as a name of a cmdlet, function, script file, or executable program.                      
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Before I actually used a template to start the project, then installed tailwind and chakra ui, at last vitest.

### Reproduction

https://github.com/WolfgangVing/website-3

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (4) x64 AMD A10-9700 RADEON R7, 10 COMPUTE CORES 4C+6G
  Memory: 1.70 GB / 7.44 GB
Binaries:
  Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
  Yarn: 3.2.4 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.52)
  Internet Explorer: 11.0.19041.1566
npmPackages:
  @vitejs/plugin-legacy: ^2.3.1 => 2.3.1
  vite: 3.2.4 => 3.2.4
  vitest: ^0.25.2 => 0.25.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
what's `vitest --config ./path/to/vitest.config.ts`
Should it be `npm run test --config ./path/to/vitest.config.ts` or `npx vitest --config ./path/to/vitest.config.ts`

**Comment by sheremet-va** [comment]
Running `vitest` will only work, if it's installed globally. I think we might update documentation to make it more obvious. PR welcome.

**Comment by TheJaredWilcurt** [comment]
Generally globally installing things via `npm` is considered an anti-pattern outside of boilerplate generators.

**Why is globally installing considered an anti-pattern? And what to do instead:**

* When you globally install `npm install -g vitest`, it will download whatever the latest version is, which may support different features than other past versions of the module that other repos may be expecting. Or may not support newer features in repos expecting a newer version than whenever you happened to do the global install
* Installing things globally can pollute your dev environment's `PATH`.
* When switching node versions using `nvm`, `nvm-windows`, `nodist` or `volta` then your globally installed packages will no longer be available. `npx vitest` will always work though (as long as you are on `npm` v5.2+, which is when `npx` was first released in 2017).

**Solutions:**

* Just `npm install --save-dev vitest` instead so that your repo has a documented, known-good, version of the module that works with the project. Then create `npm scripts` that you can run, like `npm set-script test "vitest"`. Then you can run `npm run test` like normal to execute it (or `npm t` for short).
* Just use `npx vitest` instead, it will always use the version in your project's `node_modules` if available, and if not, it defaults to the latest version, without globally or locally installing anything permanently.

**Comment by sheremet-va** [comment]
I made a mistake in my last message, I didn't mean we should recommend installing globally. I meant we should specify that `vitest` in examples is part of "scripts" field, so people don't just run "vitest" from terminal.
