### ISSUE TITLE
Entity fails instance test after being restored from a mocked module.

### ISSUE THREAD

**Issue by dmytro-grablov** [vitest-dev/vitest#2432]
### Describe the bug

If module contains a declaration of a custom error, and that error is used in the test as a part of a mocked module, that error will fail an instance test

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-tycktq?file=src/consumer.test.ts

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 85.42 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.volta/tools/image/node/16.18.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0
    Safari: 15.6.1
  npmPackages:
    vitest: 0.25.3 => 0.25.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Well, it cannot be the same, because you are mocking `./api`, and then using original `CustomError`. So, every instance of `./api` is holding different references to the actual `./api`.

When you import from `./api` you are importing from `mock:./api`. When you import actual module, you are importing from `./api`. 

You would need to use `vi.importMocked` or `import` to get the same reference.

**Comment by dmitriy-grablyov** [comment]
I turned it the other way round and do not get the mock then https://stackblitz.com/edit/node-26y25a?file=src%2Fconsumer.ts,src%2Fconsumer.test.ts
Well, I probably do not understand the concept of partial module mocking, as a person migrating from jest environment. There it is possible and exactly this way; I would, of course, not like to compare, because vitest has a different runtime, but is it possible at all (partial mocking)? And what am I doing wrong? 
In which example would `getResult` be a proper mock and `CustomError` an original error constructor from a module?

**Comment by sheremet-va** [comment]
> I turned it the other way round and do not get the mock then https://stackblitz.com/edit/node-26y25a?file=src%2Fconsumer.ts,src%2Fconsumer.test.ts
> Well, I probably do not understand the concept of partial module mocking, as a person migrating from jest environment. There it is possible and exactly this way; I would, of course, not like to compare, because vitest has a different runtime, but is it possible at all (partial mocking)? And what am I doing wrong?
> In which example would `getResult` be a proper mock and `CustomError` an original error constructor from a module?

Automocking is implemented in a different way, so you might encounter some problems with it. But your issue looks more like "I'm testing a use of a local variable, but mocking it externally", which is not possible with Vitest, and only possible in jest when using ts-jest, because it transpires the wrong output.

With your example I don't think it's possible to keep both of these in the same file, but keep Error as "original", so I would put them in a separate file.

**Comment by dmitriy-grablyov** [comment]
My example is simplified, in a real scenario a separate file would mean a separate package, extracting an error class from its own context (package) wouldn't be an option at all.

**Comment by sheremet-va** [comment]
As I said before, what you are trying to achieve is not really possible without a major rewrite.
