### ISSUE TITLE
Vitest UI opens an unexpected MacOS window 

### ISSUE THREAD

**Issue by MatteoGauthier** [vitest-dev/vitest#2518]
### Describe the bug

When i run `vitest --ui` a macos windows opens

https://user-images.githubusercontent.com/32040951/208093055-3214849c-b526-4642-a7ec-b06c35972629.mov

### Reproduction

```
git clone https://github.com/MatteoGauthier/tiles-provider.git
pnpm i ; pnpm run test:ui
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 225.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 15.6.1
  npmPackages:
    vitest: ^0.25.8 => 0.25.8 
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HiDeoo** [comment]
The window asking `Où se trouve undefined ?` (`Where is undefined?` in english) is the result of the [`openChrome.applescript`](https://github.com/vitejs/vite/blob/f12a1ab9fe6d45aa3652fef4eb777b1f72207dce/packages/vite/bin/openChrome.applescript) shipped with Vite executed with a second argument being the `"undefined"` string and this AppleScript executing [`tell application undefined`](https://github.com/vitejs/vite/blob/f12a1ab9fe6d45aa3652fef4eb777b1f72207dce/packages/vite/bin/openChrome.applescript#L24).

This was previously possible due to a missing guard before executing this AppleScript but this issue should now be fixed by https://github.com/vitejs/vite/pull/11406
