### ISSUE TITLE
Enable vite-node to run via a shebang

### ISSUE THREAD

**Issue by mrmckeb** [vitest-dev/vitest#2554]
### Clear and concise description of the problem

Using vite-node with a shebang enables no-build workflows for utilities in monorepos, which can reduce complexity and improves DX.

Usage example:
```json
{
  "scripts": {
    "start": "my-utility run --fast"
  }
}
```

This is supported in `ts-node`:
https://typestrong.org/ts-node/docs/usage/#shebang

### Suggested solution

As I understand it, `vite-node` would need two changes when running scripts this way:
- The `--` separator shouldn't be required, and all args should be considered args of the calling script.
- The `tsconfig.json` for the script should be used.

### Additional context

It looks like `ts-node` achieved this by adding a --script-mode and a new bin script.
https://github.com/TypeStrong/ts-node/commit/1ad44bf82b7e33a4dab8fcb997c891636309e89a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jgoux** [comment]
I was able to have something working writing my shebang like this:

`#!/usr/bin/env vite-node . --`

But it's definitely a hack, and I'm not sure which `tsconfig.json` file it's using actually 🤔

Also, another issue I have is that it seems like scripts run this way are cached somewhere because if I edit the source and re-run the script it executes the old content. ⁉️ 

This would definitely push `vite-node` toward being a great alternative to `ts-node` or `tsx`!
