### ISSUE TITLE
`spyOn` won't `mockReturnValue` for function being used within the same module

### ISSUE THREAD

**Issue by ThomasGormley** [vitest-dev/vitest#2961]
### Describe the bug

When trying to `mockReturnValue` for a function that is used within a function in the same module, vitest will not return the mocked value. 

### Reproduction

https://stackblitz.com/github/ThomasGormley/vitest-module-alias-bug?file=package.json

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitest: ^0.29.2 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It is expected behavior. This is not how javascript works, you cannot intercept top level variables.

**Comment by josteph** [comment]
This works in Jest so far ([link](https://github.com/facebook/jest/issues/936#issuecomment-545080082)), what's the consideration for not supporting this? It is weird to move those functions to a separate file just because we aren't able to spy/mock them in Vitest.

Or at least this should be put as a warning on https://vitest.dev/guide/migration.html#migrating-from-jest.

**Comment by sheremet-va** [comment]
> This works in Jest so far ([link](https://github.com/facebook/jest/issues/936#issuecomment-545080082)), what's the consideration for not supporting this? It is weird to move those functions to a separate file just because we aren't able to spy/mock them in Vitest.
> 
> Or at least this should be put as a warning on https://vitest.dev/guide/migration.html#migrating-from-jest.

Consideration is that it’s not how it works in JavaScrip. You cannot intercept local variables. It works with Jest only if you are using a custom transformer (because it transforms every local call into „exports.name“). If you want this supported, write your own plugin to handle transforming.

This will not be mention in the migration guide, because it’s not a standard behaviour, but a bug of the compiler.

**Comment by josteph** [comment]
Fair enough. There are maybe just too many transform tricks in Jest, so it's better to get things right from now on.

Thanks for the explanation.
