### ISSUE TITLE
Unknown file extension ".svelte" when importing Svelte files

### ISSUE THREAD

**Issue by MathiasWP** [vitest-dev/vitest#3191]
### Describe the bug

Similar to https://github.com/vitest-dev/vitest/issues/1395, but the proposed solution does not work.

I've created a minimal repro that triggers the bug, i've also given more explanation in its [readme](https://github.com/MathiasWP/vitest-unknown-file-extension-svelte-bug-repro).

### Reproduction

https://github.com/MathiasWP/vitest-unknown-file-extension-svelte-bug-repro

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 54.02 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 112.1.50.114
    Chrome: 112.0.5615.49
    Firefox: 111.0.1
    Safari: 16.4
  npmPackages:
    vite: ^4.2.0 => 4.2.1 
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You don't have a svelte plugin in your vitest config.

**Comment by MathiasWP** [comment]
> You don't have a svelte plugin in your vitest config. From the [documentation](https://vitest.dev/config/):
> 
> > Create `vitest.config.ts`, which will have the higher priority and **will override** the configuration from `vite.config.ts`

Updated repro, bug still occurs.

**Comment by MathiasWP** [comment]
> ```ts
>       inline: [/my-project-name\/dist/],
> ```

Added the regex (updated repro), now vitest throws this error:

```bash
 FAIL  tests/Button.test.ts [ tests/Button.test.ts ]
Error: Failed to load url /dist/Button.svelte (resolved id: /User/vitest-svelte-bug-repro/dist/Button.svelte) in /User/vitest-svelte-bug-repro/dist/index.js. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-79892de8.js:41096:21
```

`/User/vitest-svelte-bug-repro/dist/index.js` exports the Button.svelte like this:

```ts
export { default as Button } from './Button.svelte'
```

Why does it fail to load the url?

**Comment by sureshjoshi** [comment]
I was able to get rid of that error by changing the import to:
`import Button from '../dist/Button.svelte'`

However, the problem that arises is the same that I'm running into - which is that if there is a svelte file anywhere other than the `src` directory, it is either not compiled, or otherwise not picked up due to:

```
FAIL  tests/Button.test.ts [ tests/Button.test.ts ]
Error: Failed to load url /dist/Button.svelte (resolved id: /Users/sj/Downloads/vitest-unknown-file-extension-svelte-bug-repro-main/dist/Button.svelte) in /Users/sj/Downloads/vitest-unknown-file-extension-svelte-bug-repro-main/tests/Button.test.ts. Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@4.2.0_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-c167897e.js:41081:21
```

This is the exact same problem as it would be if you put the svelte button in your `tests` dir and tried to import it.

**Comment by MathiasWP** [comment]
I am not able to use vitest because of this bug. I am not saying that it's vitest's fault, but i am not able to figure out how to fix this. Does anyone know how to fix this?

**Comment by sureshjoshi** [comment]
I think this is a Svelte/SvelteKit thing maybe, because my root/base paths keep getting re-programmed to `src`.

I wouldn't quote me on this being the problem - but I raised it in Discord, and didn't really get any answers so far.

**Comment by dominikg** [comment]
This is really odd, why would you exclude a file from being transformed just because it is in a path that contains `dist`?

Svelte libraries are regularly exporting uncompiled .svelte files, to be compiled by the consuming application.

The official way to build these libraries is using `svelte-package` https://kit.svelte.dev/docs/packaging ,  you can generate a setup with `pnpm create svelte@latest`  and select "Library project". This setup creates a package.json where the uncompiled .svelte components are written to /dist on publish, which causes this problem.

Changing 'dist' to another name makes it work. 

What is the reasoning to treat the name `dist` differently, in dependencies or not, it's just a name as far as resolving is concerned.

**Comment by sheremet-va** [comment]
> What is the reasoning to treat the name dist differently, in dependencies or not, it's just a name as far as resolving is concerned.

Vitest assumes `node_modues`/`dist` folders have compiled code for __performance__ optimizations. If it's not compiled, Vitest will transform it even if it's in `node_modules`/`dist`. In this case, the imported file is already compiled `.js` file, so Vitest didn't process it and imported it as is. Since it's already compiled, Vitest passes down this file to be consumed by Node.js directly. After it leaves Vitest environment, it cannot go back, so since Node.js cannot consume Svelte files, it fails.

We should probably explore Node.js loader API to prevent this from happening (although it has other issues), but for now, this is how it is.

**Comment by dominikg** [comment]
> If it's not compiled, Vitest will transform it even if it's in `node_modules`/`dist`.

This is not the case for me in a pnpm monorepo with a svelte application and a svelte library, where the library is added to the application via package.json `"hello-svelte-lib":"workspace:^"`

The error is as shown in the og report:
```
 FAIL  src/routes/page.svelte.spec.ts [ src/routes/page.svelte.spec.ts ]
TypeError: Unknown file extension ".svelte" for /path/to/monorepo/hello-svelte-lib/dist/HelloButton.svelte
```
So the vite transforms are not applied to .svelte files in dist.  
Adding `/\.svelte$/` or `"hello-svelte-lib"`  didn't fix it in deps.inline either, it had to be `/hello-svelte-lib\/dist/` which i find odd. Especially given that vite-plugin-svelte puts the libraries package name into ssr.noExternal too. (note that the package name contains a namespace, `@someorg/hello-svelte-lib` so it is not present in the resolved fs path)

**Comment by sheremet-va** [comment]
> So the vite transforms are not applied to .svelte files in dist.

As I said before:

> In this case, the imported file is already compiled .js file, so Vitest didn't process it and imported it as is.

Test imports `.js` file in Node.js environment first which reexports the component. Then it follows this rule:

> After it leaves Vitest environment, it cannot go back, so since Node.js cannot consume Svelte files, it fails.

Reepxorting is done by Node.j, not Vtest. You need to inline the file that exports the component, not the component itself.

**Comment by dominikg** [comment]
dist/index.js is just a barrel reexporting the .svelte files. 
```js
export { default as HelloButton } from './HelloButton.svelte';
```
package.json exports dist/index.js via `svelte` condition
```js
	"exports": {
		".": {
			"types": "./dist/index.d.ts",
			"svelte": "./dist/index.js"
		}
	},
	"types": "./dist/index.d.ts",
	"files": [
		"dist",
		"!dist/**/*.test.*",
		"!dist/**/*.spec.*"
	],

**Comment by sheremet-va** [comment]
> dist/index.js is just a barrel reexporting the .svelte files.

Yes, and it's a `.js` file, not `.svelte` file. Vitest tells Node to consume it right away.

> Especially given that vite-plugin-svelte puts the libraries package name into ssr.noExternal too. (note that the package name contains a namespace, @someorg/hello-svelte-lib so it is not present in the resolved fs path)

Vitest inline doesn't follow the rules of Vite's `ssr.noExternal`. It's quite stupid in its implementation - it just checks the filepath. Which should probably be fixed somehow.

> there is no "compiled" content in this package and i am not sure i follow where this assumption comes from.

By "compiled" I mean the code that can be consumed by Node.js. Can this `.js` file be consumed? Yes, so Vitest delegates this to Node.js, we don't need to process it.

**Comment by sheremet-va** [comment]
Also, I am not trying to convince you that this is how it _should_ work. I am explaining how it _works_ now.

**Comment by sheremet-va** [comment]
> It's quite stupid in its implementation - it just checks the filepath. Which should probably be fixed somehow.

I am actually waiting for the `optimizeDeps.autoDiscovery` feature from patak for this, so we can just reuse SSR optimizer.

**Comment by dominikg** [comment]
> Yes, and it's a `.js` file, not `.svelte` file. Vitest tells Node to consume it right away.

but only if it resides in a directory called `dist` which feels wrong. you are giving special treatment to something that is just a common directory name, as demonstrated also used to distribute code that has to be processed by vite in a vite application you might want to test with vitest. 

> Also, I am not trying to convince you that this is how it should work. I am explaining how it works now.

Understood. I am trying to make a case that the way it works currently is based on assumptions that are not always true. And existing tools like ssr.external / ssr.noExternal should give users enough control already so that you don't have to add special treatment for anything named `dist`
