### ISSUE TITLE
Use `defineConfig` from `vitest/config` inside `vite.config.ts` in doc

### ISSUE THREAD

**Issue by DevDengChao** [vitest-dev/vitest#3572]
### Describe the bug

https://vitest.dev/config/#globals this doc says you use `defineConfig` form `vitest/config` inside a `vite.config.ts`, I'm not certain if this is intentional or a mistake.

![image](https://github.com/vitest-dev/vitest/assets/16363180/9069ea53-68c2-49c3-baf8-9b3433bf43e6)

### Reproduction

Just visit the link above.

### System Info

```shell
Not related
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arturosanz** [comment]
It is intentional. The [Vitest Config Reference](https://vitest.dev/config/) says that you have two options for the `vitest.config.ts` file. You can import `defineConfig` from either `'vite'` or `'vitest/config'`.

<img width="408" alt="Screen Shot 2023-06-15 at 5 20 48 PM" src="https://github.com/vitest-dev/vitest/assets/3165393/0e176b37-9da5-4e6a-baba-25c64668c2eb">

 However, I have problems in both cases if I import `defineConfig` from `'vite'` because I get the following type error at the `test` property.

<img width="1293" alt="Screen Shot 2023-06-15 at 5 02 52 PM" src="https://github.com/vitest-dev/vitest/assets/3165393/80f0ed37-0624-4a84-896d-c8b3d281b2f0">

<img width="854" alt="Screen Shot 2023-06-15 at 5 40 57 PM" src="https://github.com/vitest-dev/vitest/assets/3165393/ec2d3403-fd43-4985-b95f-24c8d3b26054">

I'm running `vite v2.9.16` and `vitest v0.32.0`.
