### ISSUE TITLE
TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob

### ISSUE THREAD

**Issue by asdfjkalsdfla** [vitest-dev/vitest#3985]
### Describe the bug

Starting with 0.34, tests are failing with `TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob`. While I can add node Blob in global setup like in https://github.com/vitest-dev/vitest/issues/1377#issuecomment-1141411249 , this creates inconsistent behaviors for the test vs. web based execution.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-aubhih?file=package.json,main.jsx,main.test.jsx,vite.config.js&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 5.47 GB / 7.45 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.2 - ~/node_modules/.bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.0.1 => 1.0.1
    @vitejs/plugin-react-swc: ^3.3.2 => 3.3.2
    @vitest/coverage-v8: 0.33.0 => 0.33.0
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.2 => 0.34.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jfairley** [comment]
I receive the same error originating from `URL.createObjectURL`.

Works fine in vitest 0.33.x. Breaks in 0.34.x.

![Screenshot 2023-08-28 at 9 33 28 AM](https://github.com/vitest-dev/vitest/assets/992483/95e13411-958d-4656-a87a-3769f7b2a079)

**Comment by sheremet-va** [comment]
So, it worked fine before because Vitest was using jsdom's URL which actually **doesn't support** `createObjectURL`. Node 18 now comes with an improved URL implementation which has an unfortunate side effect for the way Vitest worked before with this type of thing - using URL with Node.js API now fails because it checks the instance of the value.

To fix this, we stopped using jsdom's URL, and now only rely on Node.js URL. Looking back, I think this was the wrong decision and we will be reverting it which might introduce more problems when working with Node.js API, but it will be more consistent with how it works in the browser.

To support `createObjectURL`, you will have to polifyll it yourself.
