### ISSUE TITLE
fn2 is no a function

### ISSUE THREAD

**Issue by eduardodallmannsysmap** [vitest-dev/vitest#4132]
### Describe the bug

I'm using remix.run and vitest. In version 0.34.2 my test is working correctly. But in version 0.34.3 same test fails. The error is 'fn2 is not a function'. I understand that the error is in a dependency on remix.run, but it happens when upgrading the vitest version.

Please let me know if I should report this on remix.run.

### Reproduction

This work: https://codesandbox.io/p/sandbox/form-vitest-0-34-2-qnq6kr?file=/package.json:32,23

This fail: https://codesandbox.io/p/sandbox/form-vitest-0-34-3-rdylty?file=/package.json:32,23

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 29.33 GB / 31.19 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.7.5 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.179
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    @vitest/coverage-istanbul: ^0.34.4 => 0.34.4 
    @vitest/ui: ^0.34.4 => 0.34.4 
    vite: ^4.4.9 => 4.4.9 
    vitest: ^0.34.4 => 0.34.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by akamfoad** [comment]
Hi @eduardodallmannsysmap 

We've encountered the same issue in our team while upgrading vitest to latest on Remix 2.

Looks like the issue is happens from the formData parsing with `request.formData()`.

Since you're on Node 18, you can remove the `installGlobals` from your test setup file, Node 18 already has `fetch`, `Headers`, `Request`, `Response` and other needed globals.
You can find all globals in Node 18 here: https://nodejs.org/dist/latest-v18.x/docs/api/globals.html

You can see without the globals the tests are all passing: https://codesandbox.io/p/sandbox/form-vitest-0-34-3-forked-vyh4my?file=%2Fpackage.json%3A32%2C22

**Comment by eduardodallmannsysmap** [comment]
Thanks @akamfoad 

That was the problem, solved here
