### ISSUE TITLE
requestIdleCallback is not defined

### ISSUE THREAD

**Issue by fourdim** [vitest-dev/vitest#5027]
### Describe the bug

In 1.2.1
ReferenceError: requestIdleCallback is not defined
It works previously in 1.2.0.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-jkyzhs?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 7840HS w/ Radeon 780M Graphics
    Memory: 84.83 GB / 90.07 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.config/nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.config/nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.14.1 - ~/.config/nvm/versions/node/v20.10.0/bin/pnpm
    bun: 1.0.8 - ~/.bun/bin/bun
  Browsers:
    Chromium: 120.0.6099.199
  npmPackages:
    @vitest/browser: 1.2.1 => 1.2.1 
    @vitest/coverage-istanbul: 1.2.1 => 1.2.1 
    @vitest/ui: 1.2.1 => 1.2.1 
    vite: 5.0.12 => 5.0.12 
    vitest: 1.2.1 => 1.2.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Hey, thanks for raising an issue. Looking at the commit history in https://github.com/toeverything/blocksuite/pull/6057, it looks very reasonable to assume something happened between Vitest 1.1.3 and 1.2.1, but your reproduction is not valid since it fails regardless of versions.

While looking around your repo, I found `vi.useFakeTimers({ toFake: ['requestIdleCallback'] })` https://github.com/toeverything/blocksuite/blob/309bf43c928a54ae60105810a5a98afe78b7c2e9/packages/store/src/__tests__/workspace.unit.spec.ts#L77-L79 and that seems to be the cause. 

- 1.2.0 success https://stackblitz.com/edit/vitest-dev-vitest-g6iifx?file=test%2Frepro.test.ts
- 1.2.1 fail https://stackblitz.com/edit/vitest-dev-vitest-xtsy8w?file=test%2Frepro.test.ts

```tsx
import { vi, test, beforeAll } from 'vitest';

beforeAll(() => {
  vi.useFakeTimers({ toFake: ['requestIdleCallback'] });
});

test('repro', () => {
  requestIdleCallback(() => {});
});
```
