### ISSUE TITLE
Vitest fails to mock @okta/okta-signin-widget when no factory function is provided

### ISSUE THREAD

**Issue by iradonov** [vitest-dev/vitest#5143]
### Describe the bug

This is a really weird one, and I haven't seen anything like this with other packages, so I hope I'm missing something. The bug is related specifically to [@okta/okta-signin-widget](https://github.com/okta/okta-signin-widget), and it seems that vi.mock does not work, unless I provide a factory function to it.

It worked fine with Jest until now, which is why I got suspicious that the issue must lie in Vitest or the way I use it. 

Let me know if I should make any improvements to the reproduction.

### Reproduction

https://codesandbox.io/p/devbox/vitest-okta-mock-issue-j3x396?file=%2Fsrc%2Fokta.spec.ts%3A3%2C37

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 13.43 GB / 31.37 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE        
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.106)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @vitest/coverage-v8: ^1.2.1 => 1.2.1
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
> it seems that `vi.mock` does not work, unless I provide a factory function to it.

When calling `vi.mock` without factory function, Vitest needs to import the original one to implement the fake exports as per https://vitest.dev/guide/mocking.html#automocking-algorithm and It looks like `@okta/okta-signin-widget` is throwing during that phase since they intended to be imported only on browser environment.

Adding `environment: "happy-dom"` would make it work https://github.com/hi-ogawa/reproductions/tree/main/vitest-5143-mock-okta (https://stackblitz.com/edit/github-bkujpf?file=vitest.config.ts) but `@okta/okta-signin-widget` seems to be a huge library and loading it is slow, so using factory function to only explicitly mock used exports might be better anyways.

Btw, I think Jest's `jest.mock` would be doing same for auto-mocking, so probably you had jsdom or something setup before?

**Comment by iradonov** [comment]
Thanks! I found the issue, and luckily it's not vitest related, but because of jsdom. Closing the issue.
