### ISSUE TITLE
Warning when using with latest vite

### ISSUE THREAD

**Issue by danielroe** [vitest-dev/vitest#5211]
### Describe the bug

When using with a `customLogger` the following error is printed.

```
[warn] (!) Experimental optimizeDeps.disabled and deps pre-bundling during build were removed in Vite 5.1.
    To disable the deps optimizer, set optimizeDeps.noDiscovery to true and optimizeDeps.include as undefined or empty.
    Please remove optimizeDeps.disabled from your config.
```

### Reproduction

https://stackblitz.com/edit/github-66e6cf-qyzv3j?file=vitest.config.ts,package.json,tests/my-file.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I was wondering why warning shows up only with `customLogger`. It looks like this is because Vitest sets `logLevel: 'error'`:

https://github.com/vitest-dev/vitest/blob/9c0176087f352f80ac60b32c7954f900cb626579/packages/vitest/src/node/create.ts#L24-L25

https://github.com/vitest-dev/vitest/blob/9c0176087f352f80ac60b32c7954f900cb626579/packages/vitest/src/node/vite.ts#L14-L17

so Vite's default logger silences warnings. But when using `customLogger`, Vite doesn't apply `logLevel` filtering, so warning shows up:
https://github.com/vitejs/vite/blob/775bb5026ee1d7e15b75c8829e7f528c1b26c493/packages/vite/src/node/logger.ts#L66-L72

Of course, Vitest should deal with deprecated `optimizeDeps.disabled` flag anyways, but is it possible that Nuxt's custom logger somehow misses `logLevel` coming from Vitest's inline config?

**Comment by danielroe** [comment]
Nuxt's customLogger isn't really expecting to be used in a `vitest` environment, so it's respecting the logLevel set in the vite config that is _passed_ to it when it is created. Whereas vitest sets the logLevel _after_ the Nuxt custom logger has already been created.

I have removed the customLogger from `@nuxt/test-utils` in any case but still thought it was worth raising here.
