### ISSUE TITLE
onConsoleLog error should indicate which test the logging came from

### ISSUE THREAD

**Issue by michaellow-ca** [vitest-dev/vitest#5298]
### Clear and concise description of the problem

If we use `onConsoleLog` to handle uncaught errors, it does not seem possible to see which test the error came from.

As an example, the Apollo GraphQL client can throw a "No more mocked responses" error. This alone does not cause a test to fail in Vitest. I would like to catch these errors and ensure they fail a test.
 
By default, the test output shows me the problematic test, but does not fail.

> stderr | src/tests/MyTest.tsx > My test 
> No more mocked responses for the query...

If I update `vite.config.mts` to force an error...

```
onConsoleLog(log, type) {
   if (log.startsWith('No more mocked responses')) throw new Error(`${log}`)
}
```

The tests now fail, however it no longer indicates which file is the problem.

> Unhandled Rejection.  Error: No more mocked responses for the query...

### Suggested solution

If these outputs could be combined so `onConsoleLog` indicates the problem test, it would solve the issue.

### Alternative

Currently I use `onConsoleLog` to force an error in the case of "No more mocked responses". I then have to comment it out, re-run the test and look for the uncaught error message telling me which test it is.

### Additional context

Thank you for all your work on Vitest, it's amazing and I'm so happy to be free from Jest 😁

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Can you provide a reproduction? From the description only, I failed to see what exactly is happening in your scenario. For example,

> the Apollo GraphQL client can throw a "No more mocked responses" error. This alone does not cause a test to fail in Vitest.

I feel Vitest's default behavior is usually fails the tests on uncaught errors. So is Apollo really throwing an error? Maybe they are just doing only logging with `console.error` without throwing?

**Comment by hi-ogawa** [comment]
I have to guess but I think I understand your situation.

I think Apollo only uses `console.error` since it's not technically a hard error from Apollo's standpoint, but you want to make it hard error. In this case, (ab)using [`onConsoleLog`](https://vitest.dev/config/#onconsolelog) or custom reporter's [`onUserConsoleLog`](https://vitest.dev/advanced/reporters.html) doesn't seem appropriate since these hooks runs on main process (not during the tests). Anything you do there would be too late and I don't think you can utilize it like you imagine even if Vitest exposes more metadata to `onConsoleLog`.

For your situation, one trick came to my mind is to monkey-patch `console.error` to just catch Apollo's log inside tests:

```ts
beforeAll(() => {
  const original = console.error;
  console.error = function (...args) {
    original(...args);
    if (args[0].startsWith('No more mocked responses')) {
      throw new Error(args[0]);
    }
  }
});
```

If you think Apollo's logging should be a hard error, then maybe you can send a feature request there to provide some option to make it a hard error.
