### ISSUE TITLE
Source map resolution difference between Istanbul and V8 coverage plugins

### ISSUE THREAD

**Issue by just-boris** [vitest-dev/vitest#5341]
### Describe the bug

In our project setup, we have a pre-processing step, so the test run against a `lib` folder instead of `src`. This causes differences in behavior between `istanbul` and `v8` coverage providers.

When running tests with `istanbul` it follows the source maps and the resolves the file to the original `index.ts` source:

```
 % Coverage report from istanbul
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |
 index.ts |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
```

But it does not happen with `v8`, the report shows transpiled `index.js`

```
 % Coverage report from v8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |
 index.js |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
```

This becomes an issue when uploading reports to tools like Codecov, because they cannot match up the coverage report against the source

### Reproduction

Minimal repro can be found here: https://github.com/just-boris/vitest-coverage-issue-5341

### System Info

```shell
System:
    OS: macOS 13.6.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 594.05 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/n/bin/node
    npm: 10.2.3 - ~/n/bin/npm
  Browsers:
    Chrome: 122.0.6261.94
    Edge: 122.0.2365.63
    Safari: 17.3.1
  npmPackages:
    @vitest/coverage-istanbul: ^1.3.1 => 1.3.1
    @vitest/coverage-v8: ^1.3.1 => 1.3.1
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The root cause is in line below. V8 provider is setting the executed filename as `map.sources` without checking whether original source map had any other sources set.

https://github.com/vitest-dev/vitest/blob/6d1b145118d42b14bc0739820c4ce9e17fbd45dd/packages/coverage-v8/src/provider.ts#L333

Instead it should respect the original `map.sources` if it exists and resolve full path for that. With some quick testing the coverage looks much better. In the picture below the left side is current behavior and right one is with fixed sources. I added some uncovered if-branches to the original test code just to see that coverage reporting works after these changes:

![image](https://github.com/vitest-dev/vitest/assets/14806298/2cd7bd69-765e-4976-b574-eb8b285db9f0)
