### ISSUE TITLE
vitest hangs with stubbed process

### ISSUE THREAD

**Issue by tkalmar** [vitest-dev/vitest#5390]
### Describe the bug

Vitest hangs ( `npx vitest run`) if a test stubs the global process.
After updating vitest from 0.34 to 1.4.0
The culprit is the stubbed process, if removed everything works as expected.

### Reproduction

```
vi.stubGlobal('process', { server: false, client: true });

describe('reproducer', () => {
  it('should not hang', () => {
    expect(undefined).toBeUndefined();
  });
});
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 106.68 GB / 125.50 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  Browsers:
    Chromium: 122.0.6261.128
  npmPackages:
    @vitest/coverage-istanbul: 0.30.1 => 0.30.1 
    vitest: 1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I don't know how far we can allow manipulating globals, but for this specific case of `process`, the minimal reproduction seems to be `process.memoryUsage`:
https://stackblitz.com/edit/vitest-dev-vitest-khv9rc?file=test%2Fbasic.test.ts

```ts
process.memoryUsage = undefined;
```

I'm guessing that `memoryUsage` is used by tinypools and it's throwing inside this `try/catch`, so no result is coming back:

https://github.com/tinylibs/tinypool/blob/6ca7bb480a9d0c54dac04eaab5e6523d300f1791/src/entry/worker.ts#L126-L135

For your case, I understand it turns out to be a regression, but maybe you could also do:

```ts
vi.stubGlobal('process', { ...process, server: false, client: true });
```

Or `stubGlobal` is mostly equivalently just `process.server = false` etc... so you could simply mutate the global by yourselves.

**Comment by AriPerkkio** [comment]
We could store reference of `memoryUsage` in Tinypool before Vitest's entrypoint is imported. We do similarly in `birpc` for couple of public APIs: https://github.com/antfu/birpc/blob/72510536cedb301953e0550d884667804d7268d0/src/index.ts#L145-L147

**Comment by AriPerkkio** [comment]
https://github.com/tinylibs/tinypool/pull/83 fixes this issue. However there are still some `process` APIs that need to be saved on Vitest's side if `pool: 'forks'` is used.
