### ISSUE TITLE
Allow specifying which tests should run in browser

### ISSUE THREAD

**Issue by rChaoz** [vitest-dev/vitest#5464]
### Clear and concise description of the problem

When working with a full-stack framework such as SvelteKit, some code is intended to run on the server side and some in the browser. As such, running all unit tests on either node or browser doesn't make full sense.

### Option 1
Extra configuration options used in `describe` or `test`:

```js
describe("title", { node: false }, () => {
    // these tests run in the browser
})

describe("title", { browser: false }, () => {
    // these tests run on node
})

describe("title", () => {
    // these tests run on both
})
```

By default, both `browser` and `node` are true. When running with `vitest --browser`, the tests that are marked to run with Node only are automatically removed entirely. This also means that if a node-only test uses a mock unsupported for browsers, it wouldn't show an error. Similarly, when running without `--browser`, the browser-only tests are removed.

### Option 2
Add `test.browser.include` / `test.browser.exclude` fields for configuration. Then, all browser-related tests will be placed in separate files. I personally don't like this approach as I like to name my test files `file.test.ts` if the file tested is `file.ts`. This would also require 2 test files for a single code file, should it contain code that needs testing on both.

### Alternative

Having 2 different `vite.config.ts` files - one for regular usage + testing, one for browser testing. This allows having separate `include` and `exclude` options for node/browser testing, but is messy because:
- most of the config file is duplicated
- can't respect the `file.test.ts` naming anymore

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Our general recommendation is to use Vitest workspace features for such use cases (for example, see AriPerkkio's answer here https://github.com/vitest-dev/vitest/discussions/5461#discussioncomment-8964347).

But this will probably in the category of your "Option 2" or "Alternative" approach and you'll need to separate by test files using own conventions such as `some-file.test.browser.ts` or `some-file.test.node.ts`:

```ts
// vitest.workspace.ts
export default defineWorkspace([
  {
    // use vite.config.ts as a default config for all
    extends: "./vite.config.ts",
    test: {
      name: "node",
      include: [...defaultInclude, "**/*.test.node.ts"],
    }
  },
  {
    extends: "./vite.config.ts",
    test: {
      name: "browser",
      include: [...defaultInclude, "**/*.test.browser.ts"],
      browser: {
        enabled: true,
        name: "chrome",
      }
    }
  }
])
```

I think this approach should be practically convenient enough and I don't think introducing things like `describe(..., { node, browser })` in a single test file would be useful. For example, if you want to test some browser feature, then you cannot import node things at all in the test file (and vice versa), so I think you'll often end up having a separate test file anyways.

It would be great if you can provide more concrete examples or projects to demonstrate the usefulness of this feature. Otherwise, this would be probably an out-of-scope and we suggest using Vitest workspace features instead.

**Comment by sheremet-va** [comment]
We are not planning on making `test` function context aware. The lowest level of isolation is and will always be a file as it is much more performant and simple to understand and write.
