### ISSUE TITLE
Vitest Workspaces don't respect multiple configs in a single workspace package

### ISSUE THREAD

**Issue by conallroli** [vitest-dev/vitest#5530]
### Describe the bug

I've got a monorepo with a few packages in it. In one of those packages, I need to use two different testing setups (it's an electron app so there's both main process and renderer process setups required).

When running the tests through vitest's workspace feature, I've noticed that it gathers all the config files listed in the vitest.workspace.js file, but only uses the first config file for a given package. I've made a minimal repo [here](https://github.com/conallroli/vitest-workspace-repro)

@sheremet-va has helpfully provided a workaround to this issue. You can just put the other config file in a different folder, then adjust your `includes` as appropriate. Example [here](https://github.com/conallroli/vitest-workspace-repro/tree/move-renderer-tests-to-subfolder).

### Reproduction

https://github.com/conallroli/vitest-workspace-repro

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 65.48 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 4.1.1 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Chrome: 123.0.6312.122
    Safari: 16.3
  npmPackages:
    vitest: ^1.5.0 => 1.5.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by douglasg14b** [comment]
@sheremet-va Is this a minor bug? It's a full-stop blocker for testing with workspaces if the requirement is having two separate test setups (ie. `unit` vs `blackbox`)

**Comment by amitz** [comment]
Another vote from me about this should be prioritised higher. Even if using two separated directories as mentioned in the workaround, this is rather complex to set-up.

Consider the following structure: 

```
|-- src
|   |-- projectA
|       |-- test
|            |-- integration
|                |-- vitest.config.integration.ts
|            |-- unit
|                |-- vitest.config.unit.ts
```

For the workaround to work, the workspace directories should be `src/projectA/test/integration` and `src/projectB/test/unit`. Assuming you have tests inside, all you have to do is to set you config `include` to `**/*.spec.ts`. This will work when using Workspace to run your tests. But if you want to run the tests from the project directory (`src/projectA`) - and you're running `vitest` from that directory, the included `**/*.spec.ts` will catch both types of tests, because the working directory has changed. This can be solved with `--root`, but it's very fiddly and confusing. 

More details and a working example can be found in [here](https://github.com/vitest-dev/vitest/discussions/6280) in case anyone find it useful 😄
