### ISSUE TITLE
Cannot test object with multiple circular references

### ISSUE THREAD

**Issue by qmhc** [vitest-dev/vitest#5533]
### Describe the bug

When using `expect.toEqual` or `expect.toMatchObject` to test a object that with multiple circular references, it will make maximum call stack size exceeded error.

PS: It works in v1.1.3.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qd5xyk?file=test%2Fsuite.test.ts&view=editor

### System Info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Memory: 3.22 GB / 15.63 GB
Binaries:
  Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
  npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  pnpm: 8.15.6 - ~\AppData\Local\pnpm\pnpm.EXE
Browsers:
  Edge: Chromium (123.0.2420.81)
  Internet Explorer: 11.0.22621.1
npmPackages:
  @vitejs/plugin-vue: ^5.0.4 => 5.0.4
  @vitejs/plugin-vue-jsx: ^3.1.0 => 3.1.0
  @vitest/coverage-v8: ^1.4.0 => 1.4.0
  vite: ^5.2.8 => 5.2.8
  vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the reproduction. It looks like it got broken when we added custom equality tester in v1.2.0 https://github.com/vitest-dev/vitest/pull/4880.

The same issue can be also reproduced on Jest since the internal code is mostly same:
https://github.com/hi-ogawa/reproductions/tree/main/jest-circular-iterable

I attempted a fix https://github.com/vitest-dev/vitest/pull/5535, but while doing that, I discovered a few cases only `toMatchObject` crashes but `toEqual` succeeds. https://stackblitz.com/edit/vitest-dev-vitest-tkc5b5?file=test%2Frepro.test.ts

Jest side seems to fixed this one already:
- https://github.com/jestjs/jest/issues/14734

I'll try to address this `toMatchObject` specific issues separately.
