### ISSUE TITLE
Support import attributes in istanbul coverage

### ISSUE THREAD

**Issue by ghost** [vitest-dev/vitest#5537]
### Clear and concise description of the problem + Suggested solution

Written in next message.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
The log looks like a babel, but I don't think Vite or Vitest uses babel transform internally. The issue might be in one of your plugins which is running babel.

Can you provide a reproduction?

**Comment by 1GBpendrive** [comment]
I am not using any plugin in Vite or Vitest.

Yes, One minute, please.

Thank you.

**Comment by 1GBpendrive** [comment]
Hello @hi-ogawa
I created one StackBlitz! https://stackblitz.com/edit/vitest-dev-vitest-rwmclk

Some comments:
1. I want to use Vitest Browser Mode.
2. The setup is a Vanilla JavaScript environment, without transpilations.
3. I wanted to use  "@vitest/coverage-v8" instead of "@vitest/coverage-istanbul". However, unfortunately, Vitest Browser Mode requires "@vitest/coverage-istanbul". =/

Error message:
1. Run the script "test:run". It runs tests in Vitest Browser Mode.
2. Although the test passes, the console complains with a big error, as I wrote before. It suggests to install babel, but that is not necessary and not wanted.
3. Vite and Vitest work well with json imports, so I don't see why Vitest Browser Mode should complain about json imports. Although it is a specification in progress, it is native.

I expect this error to be gone. In other words: I expect Vitest Browser Mode to support importing .json files.

**Comment by hi-ogawa** [comment]
Thanks for the reproduction. Yeah, I couldn't find `babel` anywhere in vite, vitest or vitest browser, but indeed there's one in `@vitest/coverage-istanbul`.

It looks like a minimal repro is to run `@vitest/coverage-istanbul` with `import/assert/with` somewhere in the code. https://github.com/hi-ogawa/reproductions/tree/main/vitest-coverage-babel

This could be a bug or probably just an unfortunate limitation, so you might really need to deal with babel yourself.

**Comment by 1GBpendrive** [comment]
You are very organized. =) A github for reproductions and stackblitz too.   by the way, I enjoy your musician photo and orange t-shirt as if you were a monk.

Thank you for the clarification.
Shhh I guess I am going to see if there is an option from babel or coverage-istanbul to make this error go silent in the CLI, maybe this can be enough and things are going to work when running tests in vitest.

If things doesn't work, I may wait for this feature to be implemented then in coverage-istanbul, and consider switching back: from "vite+vite browser mode+coverage-istanbul" to "vite+happy-dom+coverage-v8" for e2e tests.

As it was mandatory to switch from v8 to istanbul, and still having to install babel, things start to be so much work hahaha.

Thank you. I understand that the problem is not in vitest.
ESLint also doesn't support Json import at the moment... but there I got a workaround. Here in babel I don't know if there is a workaround.

I hope to see the browser mode to progress in vite, as it is going to allow us to avoid playwright and happy-dom at all. Despite this import error that only affects tests that import json files, things are working very well.

**Comment by AriPerkkio** [comment]
This the Istanbul part using Babel that Vitest uses: https://github.com/istanbuljs/istanbuljs/blob/main/packages/istanbul-lib-instrument/src/instrumenter.js

Getting new improvements on Istanbul packages can be really slow - even impossible. Maybe we need to patch `istanbul-lib-instrument` and bundle it in `@vitest/coverage-istanbul`.

**Comment by Gravitonic** [comment]
It's a messy workaround, but if it helps anyone else, I was able to get Istanbul coverage with import attributes working in my setup with a couple dependency patches:

```patch
diff --git a/dist/provider.js b/dist/provider.js
index 29d6709e17e7f34614c9b2fd58053ecefd07f277..d1fbc3604dcdb519002267b10f296ae466fdd798 100644
--- a/dist/provider.js
+++ b/dist/provider.js
@@ -146,7 +146,21 @@ class IstanbulCoverageProvider extends BaseCoverageProvider {
       // @ts-expect-error missing type
       coverageGlobalScope: "globalThis",
       coverageGlobalScopeFunc: false,
-      ignoreClassMethods: this.options.ignoreClassMethods
+      ignoreClassMethods: this.options.ignoreClassMethods,
+      parserPlugins: [
+        "asyncGenerators",
+        "bigInt",
+        "classProperties",
+        "classPrivateProperties",
+        "classPrivateMethods",
+        "dynamicImport",
+        "importMeta",
+        "numericSeparator",
+        "objectRestSpread",
+        "optionalCatchBinding",
+        "topLevelAwait",
+        ["importAttributes", { deprecatedAssertSyntax: true }],
+      ]
     });
     this.testExclude = new _TestExclude({
       cwd: ctx.config.root,
```

```patch
diff --git a/CHANGELOG.md b/CHANGELOG.md
deleted file mode 100644
index 709890eceff392a3b658c039a844bfb1cf3e61c4..0000000000000000000000000000000000000000
diff --git a/src/instrumenter.js b/src/instrumenter.js
index 3322e6eb295d632a609ca950cefbcd6c6ae4776f..56c649c1761e232706949e9e1f8b22f66386f8bb 100644
--- a/src/instrumenter.js
+++ b/src/instrumenter.js
@@ -71,6 +71,7 @@ class Instrumenter {
                 sourceType: opts.esModules ? 'module' : 'script',
                 plugins: opts.parserPlugins
             },
+            generatorOpts: { importAttributesKeyword: 'with' },
             plugins: [
                 [
                     ({ types }) => {
```

(I added a bunch of `parserPlugins` but only the last one, `"importAttributes"`, is relevant to this issue; the rest I just copy-pasted from Istanbul's [defaults](https://github.com/istanbuljs/schema/blob/d7da65adc197d15e06afb3761f560507ae048495/index.js#L129-L141). There might be a better way to extend the defaults but I didn't look into it beyond finding something that worked in my setup.)

The relevant lines in `@vitest/coverage-istanbul` seem to be these, but I had to patch `istanbul-lib-instrument` as well to get it working for me.

https://github.com/vitest-dev/vitest/blob/e9ddf9ce2eaf1ce74a88f8a7ca2d8314739020ae/packages/coverage-istanbul/src/provider.ts#L109-L119

**Comment by AriPerkkio** [comment]
Awesome work @Gravitonic! Could you open a PR to https://github.com/istanbuljs repositories with these changes?
