### ISSUE TITLE
jest-extended lib seems to create duplicates inside JUnit reporter

### ISSUE THREAD

**Issue by andrii-nastenko** [vitest-dev/vitest#5662]
### Describe the bug

'jest-extended' lib seems to create duplicates inside JUnit reporter

### Reproduction

```
import * as JestExtendedMatchers from 'jest-extended/dist/matchers';

expect.extend(JestExtendedMatchers);
```

use some jest-extended matchers, for example `.toIncludeMultiple([])`

now fail this test intentionally and check JUnit report:

it will contain 2 duplicate errors:
<img width="1241" alt="Screenshot 2024-05-03 at 12 26 28" src="https://github.com/vitest-dev/vitest/assets/40956346/6bad4b89-b4c9-4826-9ed6-ed8f8051c6eb">

### System Info

```shell
jest-extended 4.0.2
vitest 1.5.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I think what appears duplicated is `Error.message` since JUnit output it to two places:

```xml
<failure message="...(here)...">
  ...(and here)...
  ...
</failure>
```

`jest-extended`'s assertion error puts everything to single `Error.message` string, so probably that's what's happening. Vitest (originally chai?) assertion error has separate `Error.message/actual/expected/diff` fields, so this doesn't happen. Here is a quick repro:
https://stackblitz.com/edit/vitest-dev-vitest-7hsjhp?file=test%2Frepro.test.ts

Is there something inconvenient about this duplicate? I suppose it's all depend on how CI platform's UI renders it, so if you have any suggestions, please feel free to share.

Currently I see multiline string in `<failure message="...">` attribute, so probably that one needs to be escaped.

**Comment by andrii-nastenko** [comment]
Hi. I thought that was somehow connected to console.logs / silent mode. 

Anyway, it doesn't bother me as much.

Thank you for investigating this!

**Comment by hi-ogawa** [comment]
Okay, this seems fine for now, so closing.
Please feel free to report again if this causes concrete issues downstream.
