### ISSUE TITLE
Option to run test suites in parallel

### ISSUE THREAD

**Issue by lcswillems** [vitest-dev/vitest#5893]
### Clear and concise description of the problem

Test suites can only be run one after the other.

### Suggested solution

Adding an option to run test suites in parallel

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Pedro-vk** [comment]
> This is implemented in v2.beta-3: #5491 Use `.concurrent`:
> 
> ```ts
> describe.concurrent('suite1')
> describe.concurrent('suite2')
> ```
I think that it is not accurate. In my case, I'm running integration tests with different configurations for each `describe`, but the runner is executing them sequentially. Still, the tests inside ("test a" or "test b") are being executed concurrently, but they must be sequential because they are integration tests. 

```ts
listOfConfigs.forEach(config => {
  describe.concurrent('suite' + config, () => {
    test("test a", () => {})
    test("test b", () => {})
  })
})
```
