### ISSUE TITLE
Allow a way to force reset the DOM between test runs in the same file

### ISSUE THREAD

**Issue by gxxcastillo** [vitest-dev/vitest#5919]
### Clear and concise description of the problem

Currently, all tests in the same file share the same global object, though it does get reset between tests in different files.

This request is to expose some function or hook, or maybe provide a setting that would allow us to reset the global object between tests in the same file.

For example, currently, if I run 5 tests in one file, where each test binds a global even handler, I'll have 5 callbacks running by the end of the test suite.

I've tried going through and copying the code that vitest uses to clear the dom between test files but it's not trivial.

### Suggested solution

I'm open to solutions here, but just some way to be able to force the reset would be great.

### Alternative

I guess an alternative could be that jsdom expose a way to do this manually given that the jsdom global is available in the testing cope.

Another alternative would be to have someone create a library that handles this.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
> I've tried going through and copying the code that vitest uses to clear the dom between test files but it's not trivial.

Vitest doesn't do any DOM specific clean ups between test files. By default each test file is isolated using [`node:worker_threads`](https://nodejs.org/api/worker_threads.html) or [`node:child_process`](https://nodejs.org/api/child_process.html) depending on [selected `pool`](https://vitest.dev/guide/improving-performance.html#improving-performance). Isolation (clean DOM) between tests is provided by terminating previous worker/thread and spinning up a new one.

If you are using `testing-library` packages, you should use their `cleanup()` method in Vitest's `afterEach()` hook. https://testing-library.com/docs/react-testing-library/api#cleanup 
Otherwise you'll need to provide your own cleanup methods manually, for example: https://github.com/AriPerkkio/aria-live-capture/blob/master/test/setup.ts.

**Comment by sheremet-va** [comment]
As @AriPerkkio already said, we already provide isolation for every test file. This is the intended design of Vitest. If there was a way to isolate global scope in test functions, we would've already used it.

Please follow @AriPerkkio advice on how to cleanup DOM in your Vitest tests, there is nothing Vitest can do on our side.

**Comment by gxxcastillo** [comment]
Hi @AriPerkkio, thanks for helping me better understand how each test file is isolated from the other.

I'm currently using the `cleanup` method from the react-testing-library but it only cleans up the react tree. Specifically from the docs: 

> Unmounts React trees that were mounted with render.

Is there no way to isolate each test?

**Comment by gxxcastillo** [comment]
While researching a solution, i found that playwright seems to offer isolation for each test. Though they seem to be leveraging browser context instead of threads and forks:

https://playwright.dev/docs/writing-tests#test-isolation

**Comment by sheremet-va** [comment]
Playwright opens a separate isolate page for every test, the test functions themselves are not isolated. Since Vitest just runs test functions, we cannot provide the same type of isolation that Playwright has.

**Comment by sheremet-va** [comment]
> If a new instance of jsdom/happy-dom/etc... were instantiated on every test case, would that solve the issue?

No, the global scope is the same.
