### ISSUE TITLE
False negative with typecheck enabled

### ISSUE THREAD

**Issue by mmkal** [vitest-dev/vitest#6151]
### Describe the bug

The following test passes!

```ts
import { expect, test } from 'vitest';

test('huh', () => {
  expect(1).toBe(2);
});
```

With this config:

```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['**/*.test.ts'],
    typecheck: {
      enabled: true,
      ignoreSourceErrors: true,
      include: ['**/*.test.ts'],
    },
  },
});
```

Note: commenting out the whole `typecheck` prop makes the test fail as expected, as does commenting out `typecheck.include`.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-hw9uz6?file=test/huh.test.ts

You can also repro with the zod repo by putting a bad assertion in one of the tests and observing that they continue to pass.

(FYI @colinhacks because of this zod might have a bunch of broken tests on the `v4` branch - that's where I found this, with vitest ^1.6.0, not sure about other branches)

Note: with `"vitest": "latest"` the "Tests" still pass but there's an unhandled error with no extra info.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitest: 2.0.3 => 2.0.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
There is a reason why `typecheck` has a separate `include` field - the test can either be one or another. The idea here is to use a separate workspace project if the files are the same (this is also how the browser mode works, for example):

```ts
export default defineWorkspace([
  {
    extends: './vitest.config.ts',
  },
  {
    extends: './vitest.config.ts',
    typecheck: {
      enabled: true,
      include: [sameInclude],
    }
  },
])
```

**Comment by mmkal** [comment]
I see, agreed would be good if there was an error to avoid false negatives. In the meantime, what would you recommend for https://github.com/colinhacks/zod/tree/v4?

That's using a vitest.root.ts: https://github.com/colinhacks/zod/blob/v4/vitest.root.ts
And then each package has a vitest.config.ts which merges vitest.root.ts with its config: https://github.com/colinhacks/zod/blob/v4/packages/zod/vitest.config.ts

Should vitest.root.ts become vitest.workspace.ts? That's what I did in this PR on zod: https://github.com/colinhacks/zod/pull/3647 - does that look about right to you? (it does seem to resolve the problem)

**Comment by colinhacks** [comment]
I ended up fixing this problem in Zod `v4` (https://github.com/colinhacks/zod/tree/v4) by adding a `types.test-d.ts` file that simply imports Zod's source code. This is a hack that was necessary to pull Zod's source code into the typechecker.

```ts
import * as z from "../src/index"

export {z};
```

It doesn't make sense to me that a file must be either be marked as "runtime tests" or "type tests". This doesn't actually seem to be true, because my test files (`*.test.ts`) are getting properly type checked when I have `typecheck.enabled = true`. But for some reason, the *source files* that are referenced by these (regular) test files doesn't get type checked. 

It seems source files only get type checked when they're imported from a `*.test-d.ts` file. I'd strongly encourage you to reconsider that design constraint. 

The pattern that most library authors want is this:

- All test files (`*.test.ts`) are executed
- All test files (`*.test.ts`) are typechecked
- All source files imported (directly or indirectly) by test files are typechecked

In trying to achieve this:

1. I naively set `typecheck.enabled = true`. But this didn't run typechecking on any of my source code. 
2. I assumed this was an issue with how files were getting included in the TS compilation, so I added a wide `typecheck.include` (`**/*.ts`) 
3. This means all my actual test files were now marked as "type test files" and my entire runtime test suite was disabled. I didn't realize this until @mmkal started digging into this, because the output still prints and it looks like everything's passing, but actually nothing is actually being executed :( That's pretty surprising, and I think it's worth reconsidering how these things interact. 

As I understand Personally I don't see much use for `*.test-d.ts` files. I have always used utilities like `expectTypeOf` alongside my other tests (in a `*.test.ts` file). In the absence of any `*.test-d.ts` files, simply setting `typecheck.enabled = true` disables all runtime tests. That's pretty unexpected and should probably be addressed.

**Comment by sheremet-va** [comment]
> It seems source files only get type checked when they're imported from a `*.test-d.ts` file. I'd strongly encourage you to reconsider that, if it's intentiional. (Correct me if I'm misunderstanding @sheremet-va)

It's a bug: https://github.com/vitest-dev/vitest/issues/5868

> The pattern that most library authors want is this

Here is the comment on why this is hard to achieve: https://github.com/vitest-dev/vitest/issues/5019#issuecomment-1917430500

----

The team agrees that it should be possible to run both at the same time:

- https://github.com/vitest-dev/vitest/issues/4766

But typechecking is low on our priorities at the moment. What I _can_ do right now is throw an error if they intersect or introduce another bug where if the do, they will just run, but the errors will be reported as source errors.

**Comment by AlexPaven** [comment]
Since the consensus seems to be typecheck and runtime tests should be able to overlap, I would urge you to reconsider excluding test.each (and the rest of the APIs that error out at typecheck); if the main problem is test names, is there a way to just use the argument to the test method, regardless of what the actual runtime name of the generated tests would be? e.g.: `test.each([1,2,3])('name $i', i => {});` would generate actual tests named name 1 etc., but for typecheck the reported test name could just be 'name %i'. I'm not familiar with vitest's code so I can't tell at a glance if that's viable or not.

I have a codebase that has a few test.each calls, and it uses types autogenerated from swagger files, it would be great if vitest could tell me immediately (as test results to keep everything under one umbrella) if any tests have typecheck errors when the types get updated - right now they pass even if vscode/typescript show type errors. But if test.each will still error out I can't enable it for the entire project.

I also tried converting test.each to for loops, and that seems to work to some extent, but the tests are no longer discoverable for example in vscode. I can probably live with that for now, or maybe the vscode extension could be improved instead to detect these tests (but I'm guessing it's not that simple). Do you know if there's any other consequences to this?
