### ISSUE TITLE
Coverage report does not include types-only TS files

### ISSUE THREAD

**Issue by igordanchenko** [vitest-dev/vitest#6164]
### Describe the bug

Discussed in #6158

In some cases, the coverage report does not include types-only `.ts` files. One particular case is when the tested file uses a types-only `.ts` file, but the types are not exported from the package barrel file. The file is not included in the report even with `all: true` in coverage settings.

### Reproduction

1) Open https://stackblitz.com/edit/vitest-v2-ts-coverage-bug-5s95pp?file=test%2Ffoo.test.ts
2) Download the sandbox to run the test locally
3) `npm install`
4) `npm run test:run`

Observe coverage report:

```
 % Coverage report from v8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 foo.ts   |     100 |      100 |     100 |     100 |                   
 index.ts |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 578.00 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.182
    Safari: 17.5
  npmPackages:
    @vitest/coverage-v8: latest => 2.0.3 
    @vitest/ui: latest => 2.0.3 
    vite: latest => 5.3.4 
    vitest: latest => 2.0.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
To summarize the bug here:
- Empty files (no runtime code, e.g. type-only) are shown in report when they are imported by test files. ✅ 
- Empty files are not shown in report when they are not imported by any test, picked by `coverage.all` ❌ 

This behavior is inconsistent. During https://github.com/vitest-dev/vitest/pull/5457 the changes of https://github.com/vitest-dev/vitest/pull/5328 should have been reverted. The #5457 implements type-only file detection is proper way while #5328 was mostly a work-around since good solution was not available back then.

This line needs to be removed and we need to make sure that the type-only files are shown properly in coverage report when they are picked by `coverage.all`. These files should not be shown as uncovered like they used to before previous fixes. 

https://github.com/vitest-dev/vitest/blob/807a2cbc4818462b9feaaecfedd0c49c6db8e4c8/packages/coverage-v8/src/provider.ts#L399-L402
