### ISSUE TITLE
Exclude all '*.config.*' files from coverage by default

### ISSUE THREAD

**Issue by Thomasan1999** [vitest-dev/vitest#6508]
### Clear and concise description of the problem

By default only a list of config files are excluded from coverage: https://github.com/vitest-dev/vitest/blob/5932a7f988fdb269ac1ae704172bc7cfbf6ed721/packages/vitest/src/defaults.ts#L18

This seems like an extra work to list all libraries which use configuration files and you still might miss some. In my case, the default config did not include `postcss.config.js` and `tailwind.config.ts` files.

### Suggested solution

I would change the mentioned line to this:
```
'**/*.config.*'
```
It would be easier to maintain and I don't think that it happens usually that someone uses `.config.` in a file name for a file they want to test. 

### Alternative

Add `tailwind` and `postcss` to the list, this would resolve my use-case but not the problem in general. The code would look like this:
```
'**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier,postcss,tailwind}.config.*'
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
> By default only a list of config files are excluded from coverage:
> https://github.com/vitest-dev/vitest/blob/5932a7f988fdb269ac1ae704172bc7cfbf6ed721/packages/vitest/src/defaults.ts#L18

That's test file exclusions. I wonder why that's even needed - doesn't make sense to have test file extensions in configuration files. 🤔 

> This seems like an extra work to list all libraries which use configuration files and you still might miss some.

Yep I agree, but adding `**/*.config.*` could cause unexpected results. I don't think we should add pattern that's this wide.

Instead of defining your `postcss.config.js` and `tailwind.config.ts` files in `coverage.exclusion`, I would rather recommend to specify `coverage.include` so that your configuration files wouldn't match it, e.g. `coverage.include: 'src'`.

**Comment by AriPerkkio** [comment]
Closing the issue as `**/*.config.*` is too wide pattern to be a default value.
