### ISSUE TITLE
Vitest fails when importing wasm module with filename.wasm?init

### ISSUE THREAD

**Issue by MCMattia** [vitest-dev/vitest#6723]
### Describe the bug

I'm importing a wasm module in a `.ts` file like so:
```
import init from '$lib/fileName.wasm?init';
```

Importing the wasm file follows the recommended way in the vite documentation:
https://vite.dev/guide/features.html#webassembly

The wasm module was compiled with emcc:
```
emcc -s EXPORTED_FUNCTIONS='["_function"]' --no-entry -std=c++20 -O1 src_cpp/file.cpp -o src/lib/fileName.wasm
```

I'm then importing a function that initializes the wasm module in a test file:
```
import {
	func
} from '$lib/file2';
import { describe, it, expect } from 'vitest';`
```

Running the test with:
```
pnpm run test
```

I get the error:
```
TypeError: Failed to parse URL from /src/lib/fileName.wasm?init
Caused by: TypeError: Invalid URL
Serialized Error: { code: 'ERR_INVALID_URL', input: '/src/lib/fileName.wasm?init' }
```

### Reproduction

Can't reproduce wasm on StackBlitz as far as I know.

### System Info

```shell
Confidential
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behaviour in Vitest because it runs code in Node.js and not in the browser by default. Node.js doesn't have a concept of a "base URL", so what Vite gives is technically not a valid URL.

See more:
- https://github.com/vitest-dev/vitest/issues/4633#issuecomment-1838621333

As you can see here, Vite expects the code to run in the browser: https://github.com/vitejs/vite/blob/dc823347bb857a9f63eee7e027a52236d7e331e0/packages/vite/src/node/plugins/wasm.ts#L32

We can try to bypass this somehow, but it might be better to run WASM tests in the [browser](https://vitest.dev/guide/browser/).

**Comment by MCMattia** [comment]
Dear @sheremet-va 

thank you a lot for your input.

I have been able to make wasm testing work with the suggested browser mode for vitest.
