### ISSUE TITLE
Disable typescript compiling when using NodeNext and --experimental-strip-types

### ISSUE THREAD

**Issue by damianobarbati** [vitest-dev/vitest#6960]
### Clear and concise description of the problem

NodeJS recently introduced the new `--experimental-strip-types` and `--experimental-transform-types` flags, allowing to `.ts` files without the need to transpile anything (types are just replaced with 1 empty space).

Full repro here: https://github.com/damianobarbati/ts-repro/

Is it possible to give the developer the option to opt-out of the build-in typescript transpiling when running vitest? 
I see unconsistent behaviours arising with imports (probably due to esnext/tsx way of handling cjs).

### Suggested solution

Give a flag to opt-out of transpiling.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
This feature is probably close to https://github.com/vitest-dev/vitest/pull/3995 in the spirit. If having an genuine and more strict node behavior is critical, we have to recommend node test runner for now.

> I see unconsistent behaviours arising with imports (probably due to esnext/tsx way of handling cjs).

This is more of resolution difference than transpilation and that's probably a harder part for Vite/Vitest to not intervene.

You can technically disable esbuild transpilation by `esbuild: false` https://vite.dev/config/shared-options.html#esbuild, but that's not enough since internally Vite expects transpiled js, so it would simply breaks.
