### ISSUE TITLE
[workaround found] Vague error - error with no location

### ISSUE THREAD

**Issue by sanjarcode** [vitest-dev/vitest#6986]
### Describe the bug

An error is shown but the trace, or at least location of the error is not shown
<img width="1008" alt="Screenshot 2024-11-29 at 6 02 45 PM" src="https://github.com/user-attachments/assets/56654f64-4906-44de-b29c-b970e5b62a80">

`TypeError: list.map is not a function` OK, but where??

### Reproduction

No repro, need to fix the error reporting sentence.

### System Info

```shell
Mac, Vite, React
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Botuca** [comment]
Hi @sanjarcode, I had the same issue today in the company's project. After debugging for a while, I managed to resolve it in two ways. My friend and colleague @elionaimelo helped me fix the problem.

In my project, I was using` Vue version 3.5.12`, `Vitest version 2.0.5`, and `vue/coverage-v8 version 2.0.5` as well. After updating `Vue to version 3.5.13` and updating both `Vitest and vue/coverage-v8 to version 2.1.6`, my project successfully ran the unit tests using the command npx vitest.

Another way to resolve the issue is to simply install the package `@vue/server-renderer` and keep the current versions of Vue and Vitest that you’re already using.

From what I understand, the new version of `Vitest (2.1.6)` now implicitly installs the `@vue/server-renderer` package, which is necessary for running unit tests correctly.

**Comment by LitenApe** [comment]
Just wanted to mention that this issue was related JSDOM if that is what you use, then that is most likely the source of the issue. Or more specifically, nwsapi

https://github.com/dperini/nwsapi/issues/135

**Comment by sheremet-va** [comment]
> From what I understand, the new version of `Vitest (2.1.6)` now implicitly installs the `@vue/server-renderer` package, which is necessary for running unit tests correctly.

Vitest doesn't install any vue packages

**Comment by CreeTar** [comment]
I have this same issue after updating to JSDOM v25 due to the punycode warning from it's tough-cookie dependency. Now all my vitest-unit tests using vue testutils are not working anymore with the same error message. The error is thrown in the jsdom-package when a selector is called, for me it's this line of code: `mountedComponent.getComponent(VTextField).get('label');`
Techstack is Vue3, Vuetify, Vite

**Comment by pratyakash** [comment]
I am also facing the same kind of Error with Next JS 14 and Vitest

**Comment by sanjarcode** [comment]
Turns out the problem is with jsdom, or atleast u can fix it by patching it.

Patch (1 line of code): https://github.com/jsdom/jsdom/pull/3797
